Add initial schema and automatic interface generation
harp-tech/device.loadcells pull request #1
Opened 2023-04-17 18:52 UTC by bruno-f-cruz

This PR adds a first schema version for the Load Cells device (device.yml) and the necessary .Net generators to build the high-level bonsai interface.

2023-05-03 09:18 UTC, artursilva0 commented on device.yml
The hardwareTargets should be 1.0 and 1.1

2023-05-03 09:19 UTC, artursilva0 requested changes
update hardwareTargets in the .yml please

2023-05-05 07:51 UTC, bruno-f-cruz commented on device.yml
We need to first support version-ranges in the schema. There is an [open issue](https://github.com/harp-tech/reflex-generator/issues/42) for it.

2023-06-28 16:38 UTC, glopesdev approved these changes

2023-06-29 22:14 UTC, merged